[project]
name = "sindy-viv"
version = "0.1.0"
description = "Scripts for a Master's thesis applying SINDy to cylinder VIV data"
readme = "README.md"
requires-python = ">=3.10"
authors = [
    { name = "Hafizh Renanto", email = "hafizhrenanto88@gmail.com" }
]
dependencies = [
    "matplotlib<=3.11.2",
    "numpy<=2.5.3",
    "pandas<=3.0.5",
    "pysindy<=2.1.0",
    "pyyaml>=6.0.3",
    "scipy<=1.18.1",
]

[project.scripts]
sindy-viv = "sindy_viv:main"

[build-system]
requires = ["uv_build>=0.12.0,<0.13.0"]
build-backend = "uv_build"
